### ISSUE TITLE
벌레 잡아주세여

### ISSUE THREAD

**Issue by 1101dawn** [ounols/APang#23]
벌레가 발견되었습니다! 두둥

1. 1-1 앙팡이 소환되는 첫번째 블럭(스폰블럭)에서 화면을 돌렸을 때 포탈 이동이 안됩니다.
 * 개인적의견 : 화면 돌렸을 때 포탈이동이 가능하니까 3-1에서처럼 포탈이 안겹쳤으면 좋겠습니다.
포탈이 겹치니까 착시 느낌도 줄어드는거 같아요.
2. 1-3 스테이지 경찰과 블럭이 겹쳐있는데 그 블럭을 누르면 앙팡이 경찰과 만나 게임오버 됩니다. (원래 블럭위로 올라가게 되어야 함)
3. 2-2 스테이지 화면을 한번도 회전하지 않은 상태에서 세번째 블럭으로 이동되지 않습니다. 회전한 후에 이동은 가능합니다.
4. 3-3 스테이지에서 밑에 있는 포탈 화면 돌렸을 때 이동이 안돼요. 확인해보니까 orthographic뷰에서 포탈블럭이 앞에 위치해 있으면 이동이 되고 뒤에 있으면 이동이 안됩니다.
5. 앙팡이 포탈 이동 할 때마다 이동후에 화면이 계속 꺼져요. (나만 그런가?

**Comment by ounols** [comment]
1번 2번 파악완료!
3, 4, 5번은 확인해보겠슴니다

**Comment by ounols** [comment]
3번 파악완료 : 윗 부분을 클릭 알고리즘 수정이 필요함
4번 파악완료 : 기획님이랑 상의 후 이 문제를 결정
